### PR TITLE
Create 5th-Week-April-2020.md

### PR DESCRIPTION
**Pull request by CryptoAmanda**
Please read, edit if need be, and approve.

### CODE REVIEW

**Review by WalterSobchakDash — APPROVED** [review]
looks good to me 👍 great job!

**Comment by essra-one** [comment]
I think that some of the administrative details are missing, but it will be alright for the public. Thank you for putting this together.

**Review by essra-one — APPROVED** [review]

**Review by unchainedio — CHANGES_REQUESTED** [review]
Amanda, can you please add a .md to the file so that readers can see the markdown.

You wrote .md in the title, but the file itself is just 5th-Week-April-2020

should be 5th-Week-April-2020.md in ur file system, the pull will change automatically, u just have to change the file name.

Here is a screenshot from your branch.

Image 2020-05-02 at 5 18 46 AM

**Comment by CryptoAmanda** [comment]
Cannot figure out how to change the commit/file name, Hytham. Have searched for answers online, nothing I've tried works. 

Will copy the file's contents word-for-word into a new commit, and merge it since four supes already approved it.

**Pull request closed without merging**
